spring:
  application:
    name: server
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL57Dialect
    url: jdbc:mysql://localhost:3306/springboot
    user: root
    password: goss123456
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true